import '../../../core/utils/money.dart';

enum InvitationTemplateTier { standard, threeD, fourD }

enum InvitationPhotoLayout {
  none,
  topHero,
  circleInset,
  fullBleed,
  floralFrame,
  splitPortrait,
}

extension InvitationTemplateTierX on InvitationTemplateTier {
  String get label => switch (this) {
        InvitationTemplateTier.standard => 'Classic',
        InvitationTemplateTier.threeD => '3D Premium',
        InvitationTemplateTier.fourD => '4D Premium',
      };

  String get badge => switch (this) {
        InvitationTemplateTier.standard => 'Included',
        InvitationTemplateTier.threeD => '3D',
        InvitationTemplateTier.fourD => '4D',
      };
}

class InvitationTemplate {
  const InvitationTemplate({
    required this.id,
    required this.name,
    required this.tier,
    required this.priceMinor,
    required this.gradientStart,
    required this.gradientEnd,
    required this.accentColor,
    this.pattern = 'floral',
    this.photoLayout = InvitationPhotoLayout.topHero,
    this.hasAnimation = false,
    this.hasParallax = false,
  });

  final String id;
  final String name;
  final InvitationTemplateTier tier;
  final int priceMinor;
  final int gradientStart;
  final int gradientEnd;
  final int accentColor;
  final String pattern;
  final InvitationPhotoLayout photoLayout;
  final bool hasAnimation;
  final bool hasParallax;

  bool get isPremium => tier != InvitationTemplateTier.standard;

  String get priceLabel =>
      priceMinor == 0 ? 'Free' : formatRevenue(priceMinor);

  String get description => switch (tier) {
        InvitationTemplateTier.standard =>
          'Photo invitation with your celebrant image, event name, and venue.',
        InvitationTemplateTier.threeD =>
          'Layered depth, motion accents, and premium typography with your photo.',
        InvitationTemplateTier.fourD =>
          'Immersive parallax, sparkle effects, and cinematic reveal with your photo.',
      };
}

/// Photo-centric invitation templates (classic + premium 3D/4D).
const kInvitationTemplates = <InvitationTemplate>[
  InvitationTemplate(
    id: 'classic-gold',
    name: 'Classic Gold',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF4B2C6F,
    gradientEnd: 0xFFD4A853,
    accentColor: 0xFFD4A853,
    pattern: 'ornate',
    photoLayout: InvitationPhotoLayout.floralFrame,
  ),
  InvitationTemplate(
    id: 'ivory-lace',
    name: 'Ivory Lace',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFFF8F7FC,
    gradientEnd: 0xFFE8D5B5,
    accentColor: 0xFF4B2C6F,
    pattern: 'lace',
    photoLayout: InvitationPhotoLayout.splitPortrait,
  ),
  InvitationTemplate(
    id: 'sunset-owanbe',
    name: 'Sunset Owanbe',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF7C2D12,
    gradientEnd: 0xFFFDBA74,
    accentColor: 0xFFDC2626,
    pattern: 'sunset',
    photoLayout: InvitationPhotoLayout.topHero,
  ),
  InvitationTemplate(
    id: 'emerald-gala',
    name: 'Emerald Gala',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF064E3B,
    gradientEnd: 0xFF6EE7B7,
    accentColor: 0xFF10B981,
    pattern: 'minimal',
    photoLayout: InvitationPhotoLayout.circleInset,
  ),
  InvitationTemplate(
    id: 'royal-purple',
    name: 'Royal Purple',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF2E1A45,
    gradientEnd: 0xFF7B4FA3,
    accentColor: 0xFFD4A853,
    pattern: 'crown',
    photoLayout: InvitationPhotoLayout.fullBleed,
  ),
  InvitationTemplate(
    id: 'blush-garden',
    name: 'Blush Garden',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFFF472B6,
    gradientEnd: 0xFFFCE7F3,
    accentColor: 0xFFBE185D,
    pattern: 'floral',
    photoLayout: InvitationPhotoLayout.floralFrame,
  ),
  InvitationTemplate(
    id: 'midnight-elegance',
    name: 'Midnight Elegance',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF0F172A,
    gradientEnd: 0xFF334155,
    accentColor: 0xFFD4A853,
    pattern: 'stars',
    photoLayout: InvitationPhotoLayout.fullBleed,
  ),
  InvitationTemplate(
    id: 'coastal-breeze',
    name: 'Coastal Breeze',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF0EA5E9,
    gradientEnd: 0xFF99F6E4,
    accentColor: 0xFF0369A1,
    pattern: 'waves',
    photoLayout: InvitationPhotoLayout.topHero,
  ),
  InvitationTemplate(
    id: 'heritage-ankara',
    name: 'Heritage Ankara',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFFB45309,
    gradientEnd: 0xFFFDE68A,
    accentColor: 0xFF92400E,
    pattern: 'ankara',
    photoLayout: InvitationPhotoLayout.circleInset,
  ),
  InvitationTemplate(
    id: 'minimal-serif',
    name: 'Minimal Serif',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFFFFFFFF,
    gradientEnd: 0xFFF1F5F9,
    accentColor: 0xFF0F172A,
    pattern: 'minimal',
    photoLayout: InvitationPhotoLayout.splitPortrait,
  ),
  InvitationTemplate(
    id: 'festive-confetti',
    name: 'Festive Confetti',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF7C3AED,
    gradientEnd: 0xFFF472B6,
    accentColor: 0xFFFBBF24,
    pattern: 'confetti',
    photoLayout: InvitationPhotoLayout.topHero,
  ),
  InvitationTemplate(
    id: 'traditional-kente',
    name: 'Traditional Kente',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF14532D,
    gradientEnd: 0xFFFACC15,
    accentColor: 0xFFDC2626,
    pattern: 'kente',
    photoLayout: InvitationPhotoLayout.floralFrame,
  ),
  InvitationTemplate(
    id: 'photo-wedding-elegance',
    name: 'Wedding Elegance',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF1E293B,
    gradientEnd: 0xFFF8FAFC,
    accentColor: 0xFFD4A853,
    pattern: 'wedding',
    photoLayout: InvitationPhotoLayout.floralFrame,
  ),
  InvitationTemplate(
    id: 'photo-birthday-party',
    name: 'Birthday Party',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFFDB2777,
    gradientEnd: 0xFFFBCFE8,
    accentColor: 0xFF7C3AED,
    pattern: 'birthday',
    photoLayout: InvitationPhotoLayout.topHero,
  ),
  InvitationTemplate(
    id: 'photo-save-the-date',
    name: 'Save the Date',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF0F172A,
    gradientEnd: 0xFF475569,
    accentColor: 0xFFFDE68A,
    pattern: 'save-date',
    photoLayout: InvitationPhotoLayout.fullBleed,
  ),
  InvitationTemplate(
    id: 'photo-garden-party',
    name: 'Garden Party',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF166534,
    gradientEnd: 0xFFBBF7D0,
    accentColor: 0xFF15803D,
    pattern: 'garden',
    photoLayout: InvitationPhotoLayout.floralFrame,
  ),
  InvitationTemplate(
    id: 'photo-golden-frame',
    name: 'Golden Frame',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFFFDF8F3,
    gradientEnd: 0xFFE8D5B5,
    accentColor: 0xFFB45309,
    pattern: 'gold-frame',
    photoLayout: InvitationPhotoLayout.splitPortrait,
  ),
  InvitationTemplate(
    id: 'photo-marble-classic',
    name: 'Marble Classic',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFFF1F5F9,
    gradientEnd: 0xFFE2E8F0,
    accentColor: 0xFF334155,
    pattern: 'marble',
    photoLayout: InvitationPhotoLayout.circleInset,
  ),
  InvitationTemplate(
    id: 'photo-cultural-heritage',
    name: 'Cultural Heritage',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF7F1D1D,
    gradientEnd: 0xFFFDE68A,
    accentColor: 0xFFB45309,
    pattern: 'heritage',
    photoLayout: InvitationPhotoLayout.floralFrame,
  ),
  InvitationTemplate(
    id: 'photo-modern-minimal',
    name: 'Modern Minimal',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF18181B,
    gradientEnd: 0xFF71717A,
    accentColor: 0xFFFAFAFA,
    pattern: 'modern',
    photoLayout: InvitationPhotoLayout.topHero,
  ),
  InvitationTemplate(
    id: 'photo-romantic-script',
    name: 'Romantic Script',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF831843,
    gradientEnd: 0xFFFDF2F8,
    accentColor: 0xFFBE185D,
    pattern: 'romantic',
    photoLayout: InvitationPhotoLayout.fullBleed,
  ),
  InvitationTemplate(
    id: 'photo-festive-kids',
    name: 'Festive Kids',
    tier: InvitationTemplateTier.standard,
    priceMinor: 0,
    gradientStart: 0xFF2563EB,
    gradientEnd: 0xFFFDE047,
    accentColor: 0xFFDC2626,
    pattern: 'kids',
    photoLayout: InvitationPhotoLayout.topHero,
  ),
  InvitationTemplate(
    id: '3d-crystal-hall',
    name: 'Crystal Hall 3D',
    tier: InvitationTemplateTier.threeD,
    priceMinor: 1500000,
    gradientStart: 0xFF1E3A5F,
    gradientEnd: 0xFF93C5FD,
    accentColor: 0xFFE0F2FE,
    pattern: '3d-hall',
    photoLayout: InvitationPhotoLayout.fullBleed,
    hasAnimation: true,
  ),
  InvitationTemplate(
    id: '3d-floral-depth',
    name: 'Floral Depth 3D',
    tier: InvitationTemplateTier.threeD,
    priceMinor: 1500000,
    gradientStart: 0xFF831843,
    gradientEnd: 0xFFFBCFE8,
    accentColor: 0xFFF472B6,
    pattern: '3d-floral',
    photoLayout: InvitationPhotoLayout.floralFrame,
    hasAnimation: true,
  ),
  InvitationTemplate(
    id: '3d-golden-gate',
    name: 'Golden Gate 3D',
    tier: InvitationTemplateTier.threeD,
    priceMinor: 1800000,
    gradientStart: 0xFF4B2C6F,
    gradientEnd: 0xFFFDE68A,
    accentColor: 0xFFD4A853,
    pattern: '3d-gate',
    photoLayout: InvitationPhotoLayout.splitPortrait,
    hasAnimation: true,
  ),
  InvitationTemplate(
    id: '3d-celebration-stage',
    name: 'Celebration Stage 3D',
    tier: InvitationTemplateTier.threeD,
    priceMinor: 1500000,
    gradientStart: 0xFF312E81,
    gradientEnd: 0xFFC4B5FD,
    accentColor: 0xFFA78BFA,
    pattern: '3d-stage',
    photoLayout: InvitationPhotoLayout.topHero,
    hasAnimation: true,
  ),
  InvitationTemplate(
    id: '4d-parallax-palace',
    name: 'Parallax Palace 4D',
    tier: InvitationTemplateTier.fourD,
    priceMinor: 3500000,
    gradientStart: 0xFF1E1B4B,
    gradientEnd: 0xFF818CF8,
    accentColor: 0xFFFDE68A,
    pattern: '4d-palace',
    photoLayout: InvitationPhotoLayout.fullBleed,
    hasAnimation: true,
    hasParallax: true,
  ),
  InvitationTemplate(
    id: '4d-starlit-vows',
    name: 'Starlit Vows 4D',
    tier: InvitationTemplateTier.fourD,
    priceMinor: 3500000,
    gradientStart: 0xFF0F172A,
    gradientEnd: 0xFF6366F1,
    accentColor: 0xFFE0E7FF,
    pattern: '4d-stars',
    photoLayout: InvitationPhotoLayout.circleInset,
    hasAnimation: true,
    hasParallax: true,
  ),
  InvitationTemplate(
    id: '4d-royal-procession',
    name: 'Royal Procession 4D',
    tier: InvitationTemplateTier.fourD,
    priceMinor: 4000000,
    gradientStart: 0xFF4B2C6F,
    gradientEnd: 0xFFDC2626,
    accentColor: 0xFFD4A853,
    pattern: '4d-royal',
    photoLayout: InvitationPhotoLayout.floralFrame,
    hasAnimation: true,
    hasParallax: true,
  ),
  InvitationTemplate(
    id: '4d-immersive-garden',
    name: 'Immersive Garden 4D',
    tier: InvitationTemplateTier.fourD,
    priceMinor: 3500000,
    gradientStart: 0xFF14532D,
    gradientEnd: 0xFF86EFAC,
    accentColor: 0xFF22C55E,
    pattern: '4d-garden',
    photoLayout: InvitationPhotoLayout.topHero,
    hasAnimation: true,
    hasParallax: true,
  ),
];

List<InvitationTemplate> templatesForTier(InvitationTemplateTier? tier) {
  if (tier == null) return kInvitationTemplates;
  return kInvitationTemplates.where((t) => t.tier == tier).toList();
}
